const mongoose = require('mongoose');
const products = [
    {
        "name": "Bajaj Ninja Series Notch 500W French Blue 3 Jar Mixer Grinder",
        "price": 4529,
        "mrp": 5329,
        "image": "image_url_here",
        "capacity": "500 Watt",
        "brand": "Bajaj",
        "description": "500 Watt Mixer Grinder in French Blue with 3 jars.",
        "caterory": "HomeAppliances",
        "keywords": ["mixer grinder", "Bajaj", "500 watt", "French blue", "3 jar", "home appliances", "kitchen appliance"],
        "model": "410600 Bajaj Ninja Series Notch 500W French Blue"
    },
    {
        "name": "Bajaj Ninja Series Elegance Purple 500W 3 Jar Mixer Grinder",
        "price": 5059,
        "mrp": 5952,
        "image": "image_url_here",
        "capacity": "500 Watt",
        "brand": "Bajaj",
        "description": "500 Watt Mixer Grinder in Purple and White with 3 jars.",
        "caterory": "HomeAppliances",
        "keywords": ["mixer grinder", "Bajaj", "500 watt", "purple", "3 jar", "home appliances", "kitchen appliance"],
        "model": "410568 Bajaj Ninja Series Elegance Purple 500W"
    },
    {
        "name": "Bajaj Military Series Duetto 500W Lilac 3 Jar Mixer Grinder",
        "price": 5412,
        "mrp": 6367,
        "image": "image_url_here",
        "capacity": "500 Watt",
        "brand": "Bajaj",
        "description": "500 Watt Mixer Grinder in Lilac and White with 3 jars.",
        "caterory": "HomeAppliances",
        "keywords": ["mixer grinder", "Bajaj", "500 watt", "lilac", "3 jar", "home appliances", "kitchen appliance"],
        "model": "410582 Bajaj Military Series Duetto 500W Lilac"
    },
    {
        "name": "Bajaj Ninja Series Carve 750W Purple 3 Jar Mixer Grinder",
        "price": 6118,
        "mrp": 7197,
        "image": "image_url_here",
        "capacity": "750 Watt",
        "brand": "Bajaj",
        "description": "750 Watt Mixer Grinder in Purple and White with 3 jars.",
        "caterory": "HomeAppliances",
        "keywords": ["mixer grinder", "Bajaj", "750 watt", "purple", "3 jar", "home appliances", "kitchen appliance"],
        "model": "410578 Bajaj Ninja Series Carve 750W Purple"
    },
    {
        "name": "Bajaj Military Series Finesse 750W Midnight Mixer Grinder",
        "price": 6206,
        "mrp": 7301,
        "image": "image_url_here",
        "capacity": "750 Watt",
        "brand": "Bajaj",
        "description": "750 Watt Mixer Grinder in Black with 3 jars.",
        "caterory": "HomeAppliances",
        "keywords": ["mixer grinder", "Bajaj", "750 watt", "black", "3 jar", "home appliances", "kitchen appliance"],
        "model": "410592 Bajaj Military Series Finesse 750W Midni"
    },
    {
        "name": "Bajaj Ninja Series Virtue 750W Black 3 Jar Mixer Grinder",
        "price": 6941,
        "mrp": 8166,
        "image": "image_url_here",
        "capacity": "750 Watt",
        "brand": "Bajaj",
        "description": "750 Watt Mixer Grinder in Black and White with 3 jars.",
        "caterory": "HomeAppliances",
        "keywords": ["mixer grinder", "Bajaj", "750 watt", "black", "3 jar", "home appliances", "kitchen appliance"],
        "model": "410594 Bajaj Ninja Series Virtue 750W Black"
    },
    {
        "name": "Bajaj Flora 1L 3KW Instant Electric Geyser",
        "price": 5882,
        "mrp": 6920,
        "image": "image_url_here",
        "capacity": "1 Litre",
        "brand": "Bajaj",
        "description": "1 Litre Instant Electric Geyser with 3KW power.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "1 litre", "3KW", "instant", "water heating"],
        "model": "150700 Flora IL 3KW "
    },
    {
        "name": "Bajaj Flora 3L IWH 3KW Instant Electric Geyser",
        "price": 6235,
        "mrp": 7336,
        "image": "image_url_here",
        "capacity": "3 Litre",
        "brand": "Bajaj",
        "description": "3 Litre Instant Electric Geyser with 3KW power.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "3 litre", "3KW", "instant", "water heating"],
        "model": "150704 Flora 3L IWH 3KW"
    },
    {
        "name": "Bajaj Astor 10L 15 Litre Storage Electric Geyser",
        "price": 11059,
        "mrp": 13010,
        "image": "image_url_here",
        "capacity": "15 Litre",
        "brand": "Bajaj",
        "description": "15 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "15 litre", "storage", "water heating"],
        "model": "150967 Astor 10L"
    },
    {
        "name": "Bajaj Astor 15L 15 Litre Storage Electric Geyser",
        "price": 11824,
        "mrp": 13910,
        "image": "image_url_here",
        "capacity": "15 Litre",
        "brand": "Bajaj",
        "description": "15 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "15 litre", "storage", "water heating"],
        "model": "150968 Astor 15L"
    },
    {
        "name": "Bajaj Astor 25L 25 Litre Storage Electric Geyser",
        "price": 13388,
        "mrp": 15751,
        "image": "image_url_here",
        "capacity": "25 Litre",
        "brand": "Bajaj",
        "description": "25 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "25 litre", "storage", "water heating"],
        "model": "150969 Astor 25L"
    },
    {
        "name": "Bajaj Shakti PC Deluxe 10L 10 Litre Storage Electric Geyser",
        "price": 11882,
        "mrp": 13979,
        "image": "image_url_here",
        "capacity": "10 Litre",
        "brand": "Bajaj",
        "description": "10 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "10 litre", "storage", "water heating"],
        "model": "150770 Shakti PC Deluxe 10L"
    },
    {
        "name": "Bajaj Shakti PC Deluxe 15L 15 Litre Storage Electric Geyser",
        "price": 12941,
        "mrp": 15225,
        "image": "image_url_here",
        "capacity": "15 Litre",
        "brand": "Bajaj",
        "description": "15 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "15 litre", "storage", "water heating"],
        "model": "150771 Shakti PC Deluxe 15L"
    },
    {
        "name": "Bajaj Shakti PC Deluxe 25L 25 Litre Storage Electric Geyser",
        "price": 14941,
        "mrp": 17578,
        "image": "image_url_here",
        "capacity": "25 Litre",
        "brand": "Bajaj",
        "description": "25 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "25 litre", "storage", "water heating"],
        "model": "150772 Shakti PC Deluxe 25L"
    },
    {
        "name": "Bajaj Majesty PC Deluxe 25L 25 Litre Storage Electric Geyser",
        "price": 16118,
        "mrp": 18962,
        "image": "image_url_here",
        "capacity": "25 Litre",
        "brand": "Bajaj",
        "description": "25 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "25 litre", "storage", "water heating"],
        "model": "150831 Majesty PC Deluxe 25L"
    },
    {
        "name": "Bajaj Mantilla 15L 15 Litre Storage Electric Geyser",
        "price": 14118,
        "mrp": 16609,
        "image": "image_url_here",
        "capacity": "15 Litre",
        "brand": "Bajaj",
        "description": "15 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "15 litre", "storage", "water heating"],
        "model": "150894 Bajaj Mantilla 15L"
    },
    {
        "name": "Bajaj Mantilla 25L 25 Litre Storage Electric Geyser",
        "price": 15882,
        "mrp": 18685,
        "image": "image_url_here",
        "capacity": "25 Litre",
        "brand": "Bajaj",
        "description": "25 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "25 litre", "storage", "water heating"],
        "model": "150895 Bajaj Mantilla 25L"
    },
    {
        "name": "Bajaj Compagno 10L 10 Litre Storage Electric Geyser",
        "price": 13529,
        "mrp": 15917,
        "image": "image_url_here",
        "capacity": "10 Litre",
        "brand": "Bajaj",
        "description": "10 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "10 litre", "storage", "water heating"],
        "model": "150856 Bajaj Compagno 10L"
    },
    {
        "name": "Bajaj Compagno 25L 25 Litre Storage Electric Geyser",
        "price": 18941,
        "mrp": 22284,
        "image": "image_url_here",
        "capacity": "25 Litre",
        "brand": "Bajaj",
        "description": "25 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "25 litre", "storage", "water heating"],
        "model": "150858 Bajaj Compagno 25L"
    },
    {
        "name": "Bajaj Maestro 10L 10 Litre Storage Electric Geyser",
        "price": 14000,
        "mrp": 16471,
        "image": "image_url_here",
        "capacity": "10 Litre",
        "brand": "Bajaj",
        "description": "10 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "10 litre", "storage", "water heating"],
        "model": "150897 Maestro 10L"
    },
    {
        "name": "Bajaj Maestro 15L 15 Litre Storage Electric Geyser",
        "price": 15176,
        "mrp": 17855,
        "image": "image_url_here",
        "capacity": "15 Litre",
        "brand": "Bajaj",
        "description": "15 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "15 litre", "storage", "water heating"],
        "model": "150898 Maestro 15L"
    },
    {
        "name": "Bajaj Maestro 25L 25 Litre Storage Electric Geyser",
        "price": 18824,
        "mrp": 22145,
        "image": "image_url_here",
        "capacity": "25 Litre",
        "brand": "Bajaj",
        "description": "25 Litre Storage Electric Geyser.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "25 litre", "storage", "water heating"],
        "model": "150899 Maestro 25"
    },
    {
        "name": "Bajaj Armor Series Pentacle 15L (BLUE) 15 Litre Storage Electric Geyser",
        "price": 15765,
        "mrp": 18547,
        "image": "image_url_here",
        "capacity": "15 Litre",
        "brand": "Bajaj",
        "description": "15 Litre Storage Electric Geyser in Blue.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "15 litre", "blue", "storage", "water heating"],
        "model": "150924 Bajaj Armor Series Pentacle 15L (BLUE)"
    },
    {
        "name": "Bajaj Armor Series Pentacle 25L (BLUE) 25 Litre Storage Electric Geyser",
        "price": 19294,
        "mrp": 22699,
        "image": "image_url_here",
        "capacity": "25 Litre",
        "brand": "Bajaj",
        "description": "25 Litre Storage Electric Geyser in Blue.",
        "caterory": "HomeAppliances",
        "keywords": ["electric geyser", "Bajaj", "25 litre", "blue", "storage", "water heating"],
        "model": "150925 Bajaj Armor Series Pentacle 25L (BLUE)"
    },
    {
        "name": "Bajaj New Popular 750 Dry Iron",
        "price": 1212,
        "mrp": 1426,
        "image": "image_url_here",
        "capacity": "750 Watt",
        "brand": "Bajaj",
        "description": "750 Watt Dry Iron in White.",
        "category": "HomeAppliances",
        "keywords": ["dry iron", "Bajaj", "750 watt", "white", "home appliances"],
        "model": "440301 Bajaj New Popular 750 Dry Iron"
    },
    {
        "name": "Bajaj DX 4 Neo Dry Iron 1000 Watt",
        "price": 1294,
        "mrp": 1522,
        "image": "image_url_here",
        "capacity": "1000 Watt",
        "brand": "Bajaj",
        "description": "1000 Watt Dry Iron in White and Blue.",
        "category": "HomeAppliances",
        "keywords": ["dry iron", "Bajaj", "1000 watt", "white", "blue", "home appliances"],
        "model": "440325 Bajaj DX 4 Neo Dry Iron"
    },
    {
        "name": "Bajaj DX 7 Neo Dry Iron 1000 Watt",
        "price": 1441,
        "mrp": 1696,
        "image": "image_url_here",
        "capacity": "1000 Watt",
        "brand": "Bajaj",
        "description": "1000 Watt Dry Iron in White and Lavender.",
        "category": "HomeAppliances",
        "keywords": ["dry iron", "Bajaj", "1000 watt", "white", "lavender", "home appliances"],
        "model": "440304 Bajaj DX 7 Neo Dry Iron"
    },
    {
        "name": "Bajaj Splendora Dry Iron 1100 Watt",
        "price": 2059,
        "mrp": 2422,
        "image": "image_url_here",
        "capacity": "1100 Watt",
        "brand": "Bajaj",
        "description": "1100 Watt Dry Iron in Red and Black.",
        "category": "HomeAppliances",
        "keywords": ["dry iron", "Bajaj", "1100 watt", "red", "black", "home appliances"],
        "model": "440314 Bajaj Splendora Dry Iron"
    },
    {
        "name": "Bajaj MX 4 Neo Steam Iron 1250 Watt",
        "price": 2235,
        "mrp": 2630,
        "image": "image_url_here",
        "capacity": "1250 Watt",
        "brand": "Bajaj",
        "description": "1250 Watt Steam Iron in Purple and White.",
        "category": "HomeAppliances",
        "keywords": ["steam iron", "Bajaj", "1250 watt", "purple", "white", "home appliances"],
        "model": "440509 Bajaj MX 4 Neo Steam Iron"
    },
    {
        "name": "Bajaj RHX 2 Room Heater 2 Rod Halogen Heater",
        "price": 2529,
        "mrp": 2976,
        "image": "image_url_here",
        "capacity": "2 Rod",
        "brand": "Bajaj",
        "description": "2 Rod Halogen Heater in White.",
        "category": "HomeAppliances",
        "keywords": ["room heater", "Bajaj", "2 rod", "halogen", "white"],
        "model": "260028 Bajaj RHX 2 Room Heater"
    },
    {
        "name": "Bajaj RH3H Room Heater 3 Rod Halogen Heater",
        "price": 4353,
        "mrp": 5121,
        "image": "image_url_here",
        "capacity": "3 Rod",
        "brand": "Bajaj",
        "description": "3 Rod Halogen Heater in Grey.",
        "category": "HomeAppliances",
        "keywords": ["room heater", "Bajaj", "3 rod", "halogen", "grey"],
        "model": "260089 Bajaj RH3H Room Heater"
    },
    {
        "name": "Bajaj RX-8 Heat Convector 2000 Watt",
        "price": 4529,
        "mrp": 5329,
        "image": "image_url_here",
        "capacity": "2000 Watt",
        "brand": "Bajaj",
        "description": "2000 Watt Heat Convector Room Heater.",
        "category": "HomeAppliances",
        "keywords": ["room heater", "Bajaj", "2000 watt", "heat convector"],
        "model": "260007 RX-8 Heat Convector"
    },
    {
        "name": "Bajaj Immersion Heater 1.5KW",
        "price": 1173,
        "mrp": 1380,
        "image": "image_url_here",
        "capacity": "1.5 KW",
        "brand": "Bajaj",
        "description": "1.5 KW Immersion Heater Rod.",
        "category": "HomeAppliances",
        "keywords": ["immersion heater", "Bajaj", "1.5 KW"],
        "model": "150650 Immersion Heater 1.5KW 25"
    },
    {
        "name": "Bajaj Water Proof Immersion Heater 1.5KW",
        "price": 1386,
        "mrp": 1630,
        "image": "image_url_here",
        "capacity": "1.5 KW",
        "brand": "Bajaj",
        "description": "1.5 KW Waterproof Immersion Heater Rod.",
        "category": "HomeAppliances",
        "keywords": ["immersion heater", "Bajaj", "waterproof", "1.5 KW"],
        "model": "150833 Water Proof Immersion Heater 1.5KW"
    }
]


module.exports = products;
