const mongoose = require('mongoose');
const products = [
    {
        category: "WashingMachines",
        name: "Haier Front Loading HW90-DM14959CS8UI [New]",
        model: "HW90-DM14959CS8UI",
        capacity: "9 Kg",
        price: 99900,
        mrp: 105000,
        description: "9 kg washing machine with Direct Motion Motor (DD Motor), 1400 RPM, 525 Super Drum, WiFi Control, AI DBS, Puri Steam, Dual Spray, I Refresh, Quick 15 wash, and memory wash program. Lifetime warranty on motor and 5 Star Energy Rating.",
        keywords: ["Haier", "Front Loading", "9 Kg", "Washing Machine", "Direct Motion Motor", "WiFi Control", "Puri Steam", "AI DBS", "I Refresh", "5 Star Rating"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "WashingMachines",
        name: "Haier Front Loading HW100-B14929S3U1 [New]",
        model: "HW100-B14929S3U1",
        capacity: "10 Kg",
        price: 110000,
        mrp: 115000,
        description: "10 kg washing machine with Direct Motion Motor (DD Motor), 1400 RPM, 525 Super Drum, WiFi Control, AI DBS, Puri Steam, Dual Spray, I Refresh, Quick 15 wash, and memory wash program. Lifetime warranty on motor and 5 Star Energy Rating.",
        keywords: ["Haier", "Front Loading", "10 Kg", "Washing Machine", "Direct Motion Motor", "WiFi Control", "Puri Steam", "AI DBS", "I Refresh", "5 Star Rating"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier HRB-3664BMT-E Bottom Mount Refrigerator",
        model: "HRB-3664BMT-E",
        capacity: "364L",
        price: 76075,
        mrp: 89500,
        description: "10 Years Warranty on Compressor, One Hour Icing Technology, Smart Display, Stabilizer Free Operation, Toughened Glass, Recessed Handle, 14 in 1 Convertible, Bottom Mount, Brush Line Silver",
        keywords: ["Haier", "364L", "Bottom Mount", "Refrigerator", "Compressor", "One Hour Icing", "Smart Display", "Energy Saving", "Toughened Glass", "Convertible"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier HRS-682KS Side by Side Refrigerator",
        model: "HRS-682KS",
        capacity: "630L",
        price: 138805,
        mrp: 163300,
        description: "10 Years Warranty on Compressor, Digital LED Display, Expert Inverter Technology, Deo Fresh Technology, Jumbo Ice Maker, Toughened Glass, Recessed Handle, 100% Convertible Fridge",
        keywords: ["Haier", "630L", "Side by Side", "Refrigerator", "Compressor", "Digital LED Display", "Expert Inverter Technology", "Deo Fresh", "Convertible Fridge"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier HRS-682SS Side by Side Refrigerator",
        model: "HRS-682SS",
        capacity: "630L",
        price: 138805,
        mrp: 163300,
        description: "10 Years Warranty on Compressor, Digital LED Display, Expert Inverter Technology, Deo Fresh Technology, Jumbo Ice Maker, Toughened Glass, Recessed Handle, 100% Convertible Fridge",
        keywords: ["Haier", "630L", "Side by Side", "Refrigerator", "Compressor", "Digital LED Display", "Expert Inverter Technology", "Deo Fresh", "Convertible Fridge"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier HRS-682EG Side by Side Refrigerator",
        model: "HRS-682EG",
        capacity: "630L",
        price: 145605,
        mrp: 171300,
        description: "10 Years Warranty on Compressor, Digital LED Display, Expert Inverter Technology, Deo Fresh Technology, Jumbo Ice Maker, Toughened Glass, Recessed Handle, 100% Convertible Fridge",
        keywords: ["Haier", "630L", "Side by Side", "Refrigerator", "Compressor", "Digital LED Display", "Expert Inverter Technology", "Deo Fresh", "Jumbo Ice Maker", "Convertible Fridge"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier HRS-692SWD Side by Side Refrigerator (New)",
        model: "HRS-692SWD",
        capacity: "628L",
        price: 152915,
        mrp: 179900,
        description: "10 Years Warranty on Compressor, Digital LED Display, Expert Inverter Technology, Deo Fresh Technology, Jumbo Ice Maker, Toughened Glass, Recessed Handle, Water Dispenser, 100% Convertible Fridge, WiFi",
        keywords: ["Haier", "628L", "Side by Side", "Refrigerator", "Compressor", "Digital LED Display", "Expert Inverter Technology", "Deo Fresh", "Jumbo Ice Maker", "Water Dispenser", "WiFi", "Convertible Fridge"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier HRT-683IS Multi Door Refrigerator",
        model: "HRT-683IS",
        capacity: "628L",
        price: 149005,
        mrp: 175300,
        description: "10 Years Warranty on Compressor, Digital LED Display, Expert Inverter Technology, Deo Fresh Technology, Jumbo Ice Maker, Toughened Glass, Recessed Handle, 83% Convertible Fridge",
        keywords: ["Haier", "628L", "Multi Door", "Refrigerator", "Compressor", "Digital LED Display", "Expert Inverter Technology", "Deo Fresh", "Jumbo Ice Maker", "Convertible Fridge"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier HRT-683FG Multi Door Refrigerator",
        model: "HRT-683FG",
        capacity: "628L",
        price: 154955,
        mrp: 182300,
        description: "10 Years Warranty on Compressor, Digital LED Display, Expert Inverter Technology, Deo Fresh Technology, Jumbo Ice Maker, Toughened Glass, Recessed Handle, 83% Convertible Fridge",
        keywords: ["Haier", "628L", "Multi Door", "Refrigerator", "Compressor", "Digital LED Display", "Expert Inverter Technology", "Deo Fresh", "Jumbo Ice Maker", "Convertible Fridge"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier Chest Freezer Hard Top Single Door HCC-148HCN [New]",
        model: "HCC-148HCN",
        capacity: "148L",
        price: 31365,
        mrp: 36900,
        description: "Compact chest freezer with a hard top, single door, and energy-saving features.",
        keywords: ["Haier", "Chest Freezer", "Hard Top", "Single Door", "148L", "Refrigerator", "Energy Saving", "Convertible"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier Chest Freezer Hard Top Single Door HCC-175HCN [New]",
        model: "HCC-175HCN",
        capacity: "175L",
        price: 35615,
        mrp: 41900,
        description: "Versatile chest freezer with a hard top, single door, and spacious design for energy-saving.",
        keywords: ["Haier", "Chest Freezer", "Hard Top", "Single Door", "175L", "Refrigerator", "Energy Saving", "Convertible"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier Chest Freezer Hard Top Single Door HFC-230SM5",
        model: "HFC-230SM5",
        capacity: "230L",
        price: 42415,
        mrp: 49900,
        description: "Spacious chest freezer with a hard top, single door, and high-density PUF for better insulation.",
        keywords: ["Haier", "Chest Freezer", "Hard Top", "Single Door", "230L", "Refrigerator", "Energy Saving", "Convertible"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier Chest Freezer Hard Top Single Door HFC-290SM5",
        model: "HFC-290SM5",
        capacity: "290L",
        price: 46665,
        mrp: 54900,
        description: "Large capacity chest freezer with a hard top and single door for better cooling retention and energy savings.",
        keywords: ["Haier", "Chest Freezer", "Hard Top", "Single Door", "290L", "Refrigerator", "Energy Saving", "Convertible"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier Chest Freezer Hard Top Single Door HFC-350DM5",
        model: "HFC-350DM5",
        capacity: "350L",
        price: 58565,
        mrp: 68900,
        description: "Efficient freezer with a hard top, single door, and energy-saving features for large storage.",
        keywords: ["Haier", "Chest Freezer", "Hard Top", "Single Door", "350L", "Refrigerator", "Energy Saving", "Convertible"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier Chest Freezer Hard Top Single Door HFC-400DMS",
        model: "HFC-400DMS",
        capacity: "400L",
        price: 63665,
        mrp: 74900,
        description: "Trapezoid door freezer with a hard top, single door, and 2 in 1 convertible technology.",
        keywords: ["Haier", "Chest Freezer", "Hard Top", "Single Door", "400L", "Refrigerator", "Energy Saving", "Convertible", "Trapezoid Door"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "Refrigerator",
        name: "Haier Chest Freezer Hard Top Single Door HFC-500DM5",
        model: "HFC-500DM5",
        capacity: "500L",
        price: 72165,
        mrp: 84900,
        description: "Large capacity chest freezer with a hard top, single door, and energy-efficient cooling.",
        keywords: ["Haier", "Chest Freezer", "Hard Top", "Single Door", "500L", "Refrigerator", "Energy Saving", "Convertible"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "WashingMachines",
        name: "Haier Front Loading HWM65 707E",
        model: "HWM65 707E",
        capacity: "6.5 Kg",
        price: 38000,
        mrp: 40000,
        description: "Advanced front-loading washing machine with 6.5 kg capacity, balance clean pulsator, and bionic magic filter.",
        keywords: ["Haier", "Front Loading", "6.5 Kg", "Washing Machine", "Balance Clean Pulsator", "LED Display", "Bionic Magic Filter"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "WashingMachines",
        name: "Haier Front Loading HWM70-306ES5 [New]",
        model: "HWM70-306ES5",
        capacity: "7 Kg",
        price: 41900,
        mrp: 44000,
        description: "7 kg front-load washing machine with advanced energy-saving features, dual magic filter, and 8 wash programs.",
        keywords: ["Haier", "Front Loading", "7 Kg", "Washing Machine", "Dual Magic Filter", "Energy Efficient", "Child Lock"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "WashingMachines",
        name: "Haier Front Loading HWM70-1269DB",
        model: "HWM70-1269DB",
        capacity: "7 Kg",
        price: 42000,
        mrp: 45000,
        description: "7 kg front-loading washing machine with a magic filter and storm pulsator for enhanced washing performance.",
        keywords: ["Haier", "Front Loading", "7 Kg", "Washing Machine", "Magic Filter", "Quick Wash", "LED Display"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "WashingMachines",
        name: "Haier Front Loading HWM80-1269DB",
        model: "HWM80-1269DB",
        capacity: "8 Kg",
        price: 47000,
        mrp: 50000,
        description: "8 kg washing machine with Oceanus Wave Drum, magic filter, and quick wash features.",
        keywords: ["Haier", "Front Loading", "8 Kg", "Washing Machine", "Oceanus Wave Drum", "Quick Wash", "LED Display"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "WashingMachines",
        name: "Haier Front Loading HWM80-678ES8 [New]",
        model: "HWM80-678ES8",
        capacity: "8 Kg",
        price: 56900,
        mrp: 60000,
        description: "8 kg front-load washing machine with a dual magic filter, in-built heater, and 3 hot water modes.",
        keywords: ["Haier", "Front Loading", "8 Kg", "Washing Machine", "Dual Magic Filter", "In-built Heater", "Energy Efficient"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "WashingMachines",
        name: "Haier Front Loading HW70 IM12929 S3",
        model: "HW70 IM12929 S3",
        capacity: "7 Kg",
        price: 78990,
        mrp: 82000,
        description: "7 kg washing machine with an inverter motor, dual spray, and laser seamless welding drum.",
        keywords: ["Haier", "Front Loading", "7 Kg", "Washing Machine", "Inverter Motor", "Laser Seamless Welding Drum"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "WashingMachines",
        name: "Haier Front Loading HW80 IM12929 EBK [New]",
        model: "HW80 IM12929 EBK",
        capacity: "8 Kg",
        price: 79900,
        mrp: 83000,
        description: "8 kg washing machine with advanced inverter motor and laser seamless welding drum for enhanced durability.",
        keywords: ["Haier", "Front Loading", "8 Kg", "Washing Machine", "Inverter Motor", "Laser Seamless Welding Drum"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "WashingMachines",
        name: "Haier Front Loading HW80 IM12929 CBK [New]",
        model: "HW80 IM12929 CBK",
        capacity: "8 Kg",
        price: 81900,
        mrp: 85000,
        description: "8 kg washing machine with an inverter motor, dual spray, and long-lasting laser seamless welding drum.",
        keywords: ["Haier", "Front Loading", "8 Kg", "Washing Machine", "Inverter Motor", "Dual Spray", "Laser Seamless Welding Drum"],
        brand: "Haier",
        image: "https://link-to-image.com"
    },
    {
        category: "WashingMachines",
        name: "Haier Front Loading HW80-DM14959CS6UI [New]",
        model: "HW80-DM14959CS6UI",
        capacity: "8 Kg",
        price: 94900,
        mrp: 98000,
        description: "8 kg washing machine featuring Direct Motion Motor (DD Motor), 1400 RPM, 525 Super Drum, WiFi Control, AI DBS, Puri Steam, Dual Spray, and I Refresh. Comes with a lifetime warranty on the motor and Quick 15 wash program.",
        keywords: ["Haier", "Front Loading", "8 Kg", "Washing Machine", "Direct Motion Motor", "WiFi Control", "Puri Steam", "AI DBS", "I Refresh", "Quick Wash", "5 Star Rating"],
        brand: "Haier",
        image: "https://link-to-image.com"
    }

];

module.exports = products;
