const mongoose = require('mongoose');
const products = [

    {
        "image": "https://www.samsungplaza.com.np/public/832-832/files/B1320AA0CE9F8C4-4…",
        "name": "UA43DU7700RSHE",
        "description": "43 inch Full HD TV with a sleek design, offering clear picture and pow…",
        "mrp": 74990,
        "price": 66700,
        "keywords": [],
        "category": "LEDTelevisions",
        "brand": "Samsung"
    },
    {

        "image": "https://www.samsungplaza.com.np/public/832-832/files/E4A59045F2E1AB3-U…",
        "name": "UA32T4340BKXXL",
        "description": "32 inch HD LED TV offering clear visuals and great audio for a compact…",
        "mrp": 41607,
        "price": 29990,
        "keywords": ["Array", "5"],
        "category": "LEDTelevisions",
        "brand": "samsung"
    },
    {

        "image": "https://www.samsungplaza.com.np/public/files/9E82A901E17B357-UA43T5400…",
        "name": "UA43T5400ARSHE",
        "description": "43 inch HD LED TV with smart features for a seamless viewing experienc…",
        "mrp": 73990,
        "price": 51200,
        "keywords": ["Array", "6"],
        "category": "LEDTelevisions",

    },
    {

        "image": "https://www.samsungplaza.com.np/public/832-832/files/1D935B85AFF0FA9-C…",
        "name": "UA43CU7700RSHE",
        "description": "43 inch Full HD LED TV with vivid colors and excellent picture quality…",
        "mrp": 74990,
        "price": 61200,
        "keywords": ["Array", "6"],
        "category": "LEDTelevisions",

    },
    {

        "image": "https://www.samsungplaza.com.np/public/832-832/files/B1320AA0CE9F8C4-4…",
        "name": "UA43DU7700RSHE",
        "description": "43 inch Full HD TV with a sleek design, offering clear picture and pow…",
        "mrp": 74990,
        "price": 66400,
        "keywords": ["Array", "6"],
        "category": "LEDTelevisions",

    },
    {

        "image": "https://www.samsungplaza.com.np/public/files/D253F77630D689C-in-crysta…",
        "name": "UA55DU7700RSHE",
        "description": "55 inch Full HD LED TV with immersive sound and vivid colors for an en…",
        "mrp": 97990,
        "price": 94500,
        "keywords": ["Array", "6"],
        "category": "LEDTelevisions",

    },
    {

        "image": "https://www.samsungplaza.com.np/public/832-832/files/F70664FEEC97239-U…",
        "name": "UA65AU7700RXHE",
        "description": "65 inch Full HD LED TV with ultra-slim design and high-quality picture…",
        "mrp": 143990,
        "price": 116700,
        "keywords": ["Array", "6"],
        "category": "LEDTelevisions",

    },
    {

        "image": "https://www.samsungplaza.com.np/public/files/1D935B85AFF0FA9-CU7700.pn…",
        "name": "UA65CU7700RSHE",
        "description": "65 inch UHD TV offering exceptional clarity, brightness, and sharp det…",
        "mrp": 143990,
        "price": 127800,
        "keywords": ["Array", "6"],
        "category": "LEDTelevisions",

    },
    {

        "image": "https://www.samsungplaza.com.np/public/832-832/files/544CD29509E7573-i…",
        "name": "UA65DU7700RSHE",
        "description": "65 inch UHD TV with vivid colors and great contrast for an immersive h…",
        "mrp": 143990,
        "price": 138900,
        "keywords": ["Array", "2"],
        "category": "LEDTelevisions",
        "capacity": "65 inches",
        "brand": "Samsung",

    }
    ,

    {
        "name": "UA65DU7700RSHE",
        "model": "UA65DU7700RSHE",
        "mrp": 143990,
        "price": 138900,
        "keywords": ["UHD", "65 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/UA65DU7700RSHE.jpg",
        "description": "65 inch UHD TV with vivid colors and great contrast for an immersive home theater experience.",
        "brand": "Samsung",
        "capacity": "65 inches"
    },
    {
        "name": "UA75DU8000RSHE",
        "model": "UA75DU8000RSHE",
        "mrp": 286990,
        "price": 233400,
        "keywords": ["UHD", "75 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/UA75DU8000RSHE.jpg",
        "description": "75 inch UHD TV offering breathtaking clarity and vibrant colors for a superior viewing experience.",
        "brand": "Samsung",
        "capacity": "75 inches"
    },
    {
        "name": "UA85BU8000RXHE",
        "model": "UA85BU8000RXHE",
        "mrp": 393990,
        "price": 338900,
        "keywords": ["UHD", "85 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/UA85BU8000RXHE.jpg",
        "description": "85 inch UHD TV with ultra-clear resolution and enhanced color accuracy for larger spaces.",
        "brand": "Samsung",
        "capacity": "85 inches"
    },
    {
        "name": "UA85CU8000RSHE",
        "model": "UA85CU8000RSHE",
        "mrp": 393990,
        "price": 361200,
        "keywords": ["UHD", "85 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/UA85CU8000RSHE.jpg",
        "description": "85 inch UHD LED TV offering enhanced viewing with deep contrast and realistic colors.",
        "brand": "Samsung",
        "capacity": "85 inches"
    },
    {
        "name": "UA85DU8000RSHE",
        "model": "UA85DU8000RSHE",
        "mrp": 393990,
        "price": 372300,
        "keywords": ["UHD", "85 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/UA85DU8000RSHE.jpg",
        "description": "85 inch UHD LED TV with superior picture quality, perfect for movie lovers and sports enthusiasts.",
        "brand": "Samsung",
        "capacity": "85 inches"
    },
    {
        "name": "QA55Q60CARXHE",
        "model": "QA55Q60CARXHE",
        "mrp": 179990,
        "price": 133400,
        "keywords": ["QLED", "55 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/QA55Q60CARXHE.jpg",
        "description": "55 inch QLED TV with stunning color accuracy, perfect for vibrant, lifelike visuals.",
        "brand": "Samsung",
        "capacity": "55 inches"
    },
    {
        "name": "QA55Q60CARSHE",
        "model": "QA55Q60CARSHE",
        "mrp": 179990,
        "price": 133400,
        "keywords": ["QLED", "55 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/QA55Q60CARSHE.jpg",
        "description": "55 inch QLED TV with Quantum Dot technology, delivering rich colors and crystal-clear clarity.",
        "brand": "Samsung",
        "capacity": "55 inches"
    },
    {
        "name": "QA55Q60DARSHE",
        "model": "QA55Q60DARSHE",
        "mrp": 179990,
        "price": 144400,
        "keywords": ["QLED", "55 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/QA55Q60DARSHE.jpg",
        "description": "55 inch QLED TV with Dynamic Crystal Color for enhanced brightness and color details.",
        "brand": "Samsung",
        "capacity": "55 inches"
    },
    {
        "name": "QA65Q60CARSHE",
        "model": "QA65Q60CARSHE",
        "mrp": 250990,
        "price": 200000,
        "keywords": ["QLED", "65 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/QA65Q60CARSHE.jpg",
        "description": "65 inch QLED TV with amazing contrast and immersive audio for an exceptional viewing experience.",
        "brand": "Samsung",
        "capacity": "65 inches"
    },
    {
        "name": "QA65Q60DARSHE",
        "model": "QA65Q60DARSHE",
        "mrp": 250990,
        "price": 222300,
        "keywords": ["QLED", "65 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/QA65Q60DARSHE.jpg",
        "description": "65 inch QLED TV with Dynamic HDR for stunning picture quality and clear, vibrant details.",
        "brand": "Samsung",
        "capacity": "65 inches"
    },
    {
        "name": "QA75Q60CARSHE",
        "model": "QA75Q60CARSHE",
        "mrp": 340990,
        "price": 266700,
        "keywords": ["QLED", "75 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/QA75Q60CARSHE.jpg",
        "description": "75 inch QLED TV offering deep blacks and brighter whites, perfect for large home theaters.",
        "brand": "Samsung",
        "capacity": "75 inches"
    },
    {
        "name": "QA75Q60DARSHE",
        "model": "QA75Q60DARSHE",
        "mrp": 340990,
        "price": 283400,
        "keywords": ["QLED", "75 inch"],
        "category": "LEDTelevisions",
        "image": "http://example.com/images/QA75Q60DARSHE.jpg",
        "description": "75 inch QLED TV with Dynamic Crystal Color for brighter whites and deeper blacks, delivering cinematic quality in your living room.",
        "brand": "Samsung",
        "capacity": "75 inches"
    },
    {
        "name": "RR20C20C2GS/IM",
        "model": "RR20C20C2GS/IM",
        "mrp": 33490,
        "price": 28500,
        "keywords": ["Single Door", "192 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RR20C20C2GS/IM.jpg",
        "description": "192 L Single Door Refrigerator with a sleek design and energy-efficient cooling system, perfect for smaller households.",
        "brand": "Samsung",
        "capacity": "192 L"
    },
    {
        "name": "RR20C20C2RH/IM",
        "model": "RR20C20C2RH/IM",
        "mrp": 32990,
        "price": 27500,
        "keywords": ["Single Door", "192 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RR20C20C2RH/IM.jpg",
        "description": "192 L Single Door Refrigerator with a reliable cooling system, keeping your food fresh for longer in a compact form.",
        "brand": "Samsung",
        "capacity": "192 L"
    },
    {
        "name": "RR20C241258/IM",
        "model": "RR20C241258/IM",
        "mrp": 36990,
        "price": 31500,
        "keywords": ["Single Door", "192 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RR20C241258/IM.jpg",
        "description": "192 L Single Door Refrigerator with an efficient compressor and spacious storage, ideal for a small family or single-user.",
        "brand": "Samsung",
        "capacity": "192 L"
    },
    {
        "name": "RR20C2722CR/IM",
        "model": "RR20C2722CR/IM",
        "mrp": 37990,
        "price": 32500,
        "keywords": ["Single Door", "192 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RR20C2722CR/IM.jpg",
        "description": "192 L Single Door Refrigerator with a modern design and energy-saving features, perfect for modern homes.",
        "brand": "Samsung",
        "capacity": "192 L"
    },
    {
        "name": "RR20C2722CU/IM",
        "model": "RR20C2722CU/IM",
        "mrp": 37990,
        "price": 32500,
        "keywords": ["Single Door", "192 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RR20C2722CU/IM.jpg",
        "description": "192 L Single Door Refrigerator with advanced cooling technology and minimalistic design for a better kitchen aesthetic.",
        "brand": "Samsung",
        "capacity": "192 L"
    },
    {
        "name": "RR20C2Z226R/IM",
        "model": "RR20C2Z226R/IM",
        "mrp": 39590,
        "price": 33500,
        "keywords": ["Single Door", "192 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RR20C2Z226R/IM.jpg",
        "description": "192 L Single Door Refrigerator featuring a spacious interior and a modern design to keep your food fresh and organized.",
        "brand": "Samsung",
        "capacity": "192 L"
    },
    {
        "name": "RR20C2Z226U/IM",
        "model": "RR20C2Z226U/IM",
        "mrp": 39590,
        "price": 33500,
        "keywords": ["Single Door", "192 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RR20C2Z226U/IM.jpg",
        "description": "192 L Single Door Refrigerator with an efficient compressor and durable build, providing value for money.",
        "brand": "Samsung",
        "capacity": "192 L"
    },
    {
        "name": "RR20M282ZS8/IM",
        "model": "RR20M282ZS8/IM",
        "mrp": 38990,
        "price": 33000,
        "keywords": ["Single Door", "192 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RR20M282ZS8/IM.jpg",
        "description": "192 L Single Door Refrigerator with a sleek finish and spacious storage, ideal for everyday household needs.",
        "brand": "Samsung",
        "capacity": "192 L"
    },
    {
        "name": "RR20T282ZR8/IM",
        "model": "RR20T282ZR8/IM",
        "mrp": 41990,
        "price": 36000,
        "keywords": ["Single Door", "192 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RR20T282ZR8/IM.jpg",
        "description": "192 L Single Door Refrigerator with a contemporary design and efficient cooling to preserve your food for longer.",
        "brand": "Samsung",
        "capacity": "192 L"
    },
    {
        "name": "RR20T282ZU8/IM",
        "model": "RR20T282ZU8/IM",
        "mrp": 41990,
        "price": 36000,
        "keywords": ["Single Door", "192 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RR20T282ZU8/IM.jpg",
        "description": "192 L Single Door Refrigerator with innovative features for better storage and energy-efficient performance.",
        "brand": "Samsung",
        "capacity": "192 L"
    },
    {
        "name": "RR24A272ZCU/IM",
        "model": "RR24A272ZCU/IM",
        "mrp": 44990,
        "price": 38200,
        "keywords": ["Single Door", "230 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RR24A272ZCU/IM.jpg",
        "description": "230 L Single Door Refrigerator designed to deliver superior cooling while offering more space for your food.",
        "brand": "Samsung",
        "capacity": "230 L"
    },
    {
        "name": "RT28A3022GS/IM",
        "model": "RT28A3022GS/IM",
        "mrp": 56490,
        "price": 46500,
        "keywords": ["Double Door", "253 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT28A3022GS/IM.jpg",
        "description": "253 L Double Door Refrigerator with a sleek design, fast cooling, and better space management for large families.",
        "brand": "Samsung",
        "capacity": "253 L"
    },
    {
        "name": "RT28A32216U/IM",
        "model": "RT28A32216U/IM",
        "mrp": 60990,
        "price": 51000,
        "keywords": ["Double Door", "253 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT28A32216U/IM.jpg",
        "description": "253 L Double Door Refrigerator with advanced features like energy-saving technology and better food preservation.",
        "brand": "Samsung",
        "capacity": "253 L"
    },
    {
        "name": "RT28A32216R/IM",
        "model": "RT28A32216R/IM",
        "mrp": 60990,
        "price": 51000,
        "keywords": ["Double Door", "253 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT28A32216R/IM.jpg",
        "description": "253 L Double Door Refrigerator with enhanced cooling performance and energy-efficient technology.",
        "brand": "Samsung",
        "capacity": "253 L"
    },
    {
        "name": "RT28C3221CR/IM",
        "model": "RT28C3221CR/IM",
        "mrp": 61990,
        "price": 51500,
        "keywords": ["Double Door", "253 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT28C3221CR/IM.jpg",
        "description": "253 L Double Door Refrigerator featuring a modern look and improved cooling system for long-lasting freshness.",
        "brand": "Samsung",
        "capacity": "253 L"
    },
    {
        "name": "RT28C3221CU/IM",
        "model": "RT28C3221CU/IM",
        "mrp": 61990,
        "price": 51500,
        "keywords": ["Double Door", "253 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT28C3221CU/IM.jpg",
        "description": "253 L Double Door Refrigerator with enhanced storage options and effective cooling technology.",
        "brand": "Samsung",
        "capacity": "253 L"
    },
    {
        "name": "RT30K334258/IM",
        "model": "RT30K334258/IM",
        "mrp": 67990,
        "price": 55500,
        "keywords": ["Double Door", "275 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT30K334258/IM.jpg",
        "description": "275 L Double Door Refrigerator with improved storage, energy efficiency, and a stylish look for modern kitchens.",
        "brand": "Samsung",
        "capacity": "275 L"
    },
    {
        "name": "RT37C4521S8/IM",
        "model": "RT37C4521S8/IM",
        "mrp": 84990,
        "price": 71000,
        "keywords": ["5 in 1", "345 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT37C4521S8/IM.jpg",
        "description": "345 L 5-in-1 Refrigerator with a convertible design offering versatile storage options and efficient cooling.",
        "brand": "Samsung",
        "capacity": "345 L"
    },
    {
        "name": "RT39C5531S8/IM",
        "model": "RT39C5531S8/IM",
        "mrp": 108990,
        "price": 98091,
        "keywords": ["5 in 1", "394 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT39C5531S8/IM.jpg",
        "description": "394 L 5-in-1 Refrigerator with convertible features, designed for spacious storage and energy-efficient cooling.",
        "brand": "Samsung",
        "capacity": "394 L"
    },
    {
        "name": "RT42C553258/IM",
        "model": "RT42C553258/IM",
        "mrp": 116490,
        "price": 104841,
        "keywords": ["5 in 1", "415 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT42C553258/IM.jpg",
        "description": "415 L 5-in-1 Refrigerator with multiple cooling modes and a spacious interior to store all your food items.",
        "brand": "Samsung",
        "capacity": "415 L"
    },
    {
        "name": "RT47K6358SL/TL",
        "model": "RT47K6358SL/TL",
        "mrp": 164990,
        "price": 120500,
        "keywords": ["5 in 1", "465 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT47K6358SL/TL.jpg",
        "description": "465 L 5-in-1 Refrigerator with sleek design, perfect for large families, providing optimized cooling and energy savings.",
        "brand": "Samsung",
        "capacity": "465 L"
    },
    {
        "name": "RT49K6338BS/TL",
        "model": "RT49K6338BS/TL",
        "mrp": 169990,
        "price": 127192,
        "keywords": ["5 in 1", "478 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT49K6338BS/TL.jpg",
        "description": "478 L 5-in-1 Refrigerator designed to meet large storage needs with enhanced cooling options and multiple modes.",
        "brand": "Samsung",
        "capacity": "478 L"
    },
    {
        "name": "RT54K6558SL/TL",
        "model": "RT54K6558SL/TL",
        "mrp": 189990,
        "price": 151992,
        "keywords": ["5 in 1", "523 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT54K6558SL/TL.jpg",
        "description": "523 L 5-in-1 Refrigerator with ultra-spacious design, ideal for large households, offering superior cooling performance.",
        "brand": "Samsung",
        "capacity": "523 L"
    },
    {
        "name": "RT56K6378SL/TL",
        "model": "RT56K6378SL/TL",
        "mrp": 194990,
        "price": 151992,
        "keywords": ["5 in 1", "551 L"],
        "category": "Refrigerators",
        "image": "http://example.com/images/RT56K6378SL/TL.jpg",
        "description": "551 L 5-in-1 Refrigerator with the largest capacity, multiple cooling options for flexible storage and efficiency.",
        "brand": "Samsung",
        "capacity": "551 L"
    },
    {
        "name": "WT70M3200HB/TL",
        "model": "WT70M3200HB/TL",
        "mrp": 25990,
        "price": 23000,
        "keywords": ["Semi-Automatic Top Load", "7 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WT70M3200HB/TL.jpg",
        "description": "7 Kg Semi-Automatic Top Load Washing Machine, compact design and efficient wash cycles for everyday laundry.",
        "brand": "Samsung",
        "capacity": "7 Kg"
    },
    {
        "name": "WT70M3200LL/TL",
        "model": "WT70M3200LL/TL",
        "mrp": 25990,
        "price": 23000,
        "keywords": ["Semi-Automatic Top Load", "7 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WT70M3200LL/TL.jpg",
        "description": "7 Kg Semi-Automatic Top Load Washing Machine with advanced features for efficient and quick washing.",
        "brand": "Samsung",
        "capacity": "7 Kg"
    },
    {
        "name": "WT70M3000HP/TL",
        "model": "WT70M3000HP/TL",
        "mrp": 25990,
        "price": 23000,
        "keywords": ["Semi-Automatic Top Load", "7 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WT70M3000HP/TL.jpg",
        "description": "7 Kg Semi-Automatic Top Load Washing Machine with powerful washing technology for a superior laundry experience.",
        "brand": "Samsung",
        "capacity": "7 Kg"
    },
    {
        "name": "WA80BG4441BD/IM",
        "model": "WA80BG4441BD/IM",
        "mrp": 49990,
        "price": 42778,
        "keywords": ["Fully Automatic Top Load", "8 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WA80BG4441BD/IM.jpg",
        "description": "8 Kg Fully Automatic Top Load Washing Machine with advanced washing modes for optimal cleaning results.",
        "brand": "Samsung",
        "capacity": "8 Kg"
    },
    {
        "name": "WA80BG4545BV/IM",
        "model": "WA80BG4545BV/IM",
        "mrp": 56990,
        "price": 49444,
        "keywords": ["Fully Automatic Top Load", "8 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WA80BG4545BV/IM.jpg",
        "description": "8 Kg Fully Automatic Top Load Washing Machine with multi-wash programs and an energy-efficient motor.",
        "brand": "Samsung",
        "capacity": "8 Kg"
    },
    {
        "name": "WW80TA046AX/IM",
        "model": "WW80TA046AX/IM",
        "mrp": 101990,
        "price": 76000,
        "keywords": ["EcobubbleTM Front Load", "8 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WW80TA046AX/IM.jpg",
        "description": "8 Kg EcobubbleTM Front Load Washing Machine with advanced bubble technology for gentle yet effective cleaning.",
        "brand": "Samsung",
        "capacity": "8 Kg"
    },
    {
        "name": "WW80TA046AE/IM",
        "model": "WW80TA046AE/IM",
        "mrp": 89990,
        "price": 73000,
        "keywords": ["EcobubbleTM Front Load", "8 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WW80TA046AE/IM.jpg",
        "description": "8 Kg EcobubbleTM Front Load Washing Machine with energy-saving and water-efficient features for modern homes.",
        "brand": "Samsung",
        "capacity": "8 Kg"
    },
    {
        "name": "WW80T504DAN/IM",
        "model": "WW80T504DAN/IM",
        "mrp": 117990,
        "price": 81000,
        "keywords": ["EcobubbleTM Front Load", "8 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WW80T504DAN/IM.jpg",
        "description": "8 Kg EcobubbleTM Front Load Washing Machine with Smart Control and advanced wash cycles for better care of your clothes.",
        "brand": "Samsung",
        "capacity": "8 Kg"
    },
    {
        "name": "WW80T504DAB/IM",
        "model": "WW80T504DAB/IM",
        "mrp": 117990,
        "price": 83000,
        "keywords": ["AI EcobubbleTM Front Load", "8 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WW80T504DAB/IM.jpg",
        "description": "8 Kg AI EcobubbleTM Front Load Washing Machine with advanced AI-powered cleaning for efficient fabric care.",
        "brand": "Samsung",
        "capacity": "8 Kg"
    },
    {
        "name": "WW90T504DAN/IM",
        "model": "WW90T504DAN/IM",
        "mrp": 125990,
        "price": 95000,
        "keywords": ["AI EcobubbleTM Front Load", "9 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WW90T504DAN/IM.jpg",
        "description": "9 Kg AI EcobubbleTM Front Load Washing Machine with large capacity and intelligent fabric care.",
        "brand": "Samsung",
        "capacity": "9 Kg"
    },
    {
        "name": "WW12TP94DSX/SP",
        "model": "WW12TP94DSX/SP",
        "mrp": 153990,
        "price": 127000,
        "keywords": ["AI EcobubbleTM Front Load", "12 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WW12TP94DSX/SP.jpg",
        "description": "12 Kg AI EcobubbleTM Front Load Washing Machine with ultra-large capacity for families, ensuring gentle yet effective washing.",
        "brand": "Samsung",
        "capacity": "12 Kg"
    },
    {
        "name": "WD90T634DBN/SP",
        "model": "WD90T634DBN/SP",
        "mrp": 132990,
        "price": 102000,
        "keywords": ["AI EcobubbleTM Washer Dryer", "9 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WD90T634DBN/SP.jpg",
        "description": "9 Kg AI EcobubbleTM Washer Dryer with both washing and drying capabilities, perfect for small to medium households.",
        "brand": "Samaung",
        "capacity": "9 Kg"
    },
    {
        "name": "WD11TP34DSX/FQ",
        "model": "WD11TP34DSX/FQ",
        "mrp": 151990,
        "price": 122000,
        "keywords": ["AI EcobubbleTM Washer Dryer", "11 Kg"],
        "category": "WashingMachines",
        "image": "http://example.com/images/WD11TP34DSX/FQ.jpg",
        "description": "11 Kg AI EcobubbleTM Washer Dryer with advanced washing and drying options, featuring EcoBubble technology for energy efficiency.",
        "brand": "Samsung",
        "capacity": "11 Kg"
    },
    {
        "category": "Refrigerators",
        "dp": "30,990.00",
        "description": "Transparent Interior, Wired Shelves, 10 years compressor warranty, anti bacterial gasket, Fastest Ice making",
        "brand": "LG",
        "name": "GLB198RDGU",
        "image": "URL to Image",
        "capacity": "190L",
        "keywords": ["Single Door", "Transparent", "Anti Bacterial", "Fast Ice Making"],
        "model": "GLB198RDGU",
        "mrp": "33,190.00"
    },
    {
        "category": "Refrigerators",
        "dp": "31,490.00",
        "description": "Peppy Red, Toughened Glass, 10 yrs Compressor Warranty, Moist Balance Crisper, Anti Bacterial Gasket, Door handle",
        "brand": "LG",
        "name": "GLB200RPR",
        "image": "URL to Image",
        "capacity": "200L",
        "keywords": ["Peppy Red", "Moist Balance", "Anti Bacterial", "Toughened Glass"],
        "model": "GLB200RPR",
        "mrp": "34,090.00"
    },
    {
        "category": "Refrigerators",
        "dp": "32,490.00",
        "description": "Smart Inverter Compressor, 10 Yrs. Compressor warranty, Transparent Interior, Wired Shelf, Fastest Ice Making, Anti-bacterial gasket, LVS(90v-310v)",
        "brand": "LG",
        "name": "GL-B200HRLN",
        "image": "URL to Image",
        "capacity": "200L",
        "keywords": ["Smart Inverter", "Wired Shelf", "Anti-bacterial", "LVS Range"],
        "model": "GL-B200HRLN",
        "mrp": "35,190.00"
    },
    {
        "category": "Refrigerators",
        "dp": "33,490.00",
        "description": "Smart Inverter Compressor, 10 Yrs. Compressor warranty, Transparent Interior, Toughened Glass, Fastest Ice Making, LVS(100v-290v)",
        "brand": "LG",
        "name": "GLB201ALLB.APZQ",
        "image": "URL to Image",
        "capacity": "210L",
        "keywords": ["Smart Inverter", "Toughened Glass", "Fast Ice Making", "LVS Range"],
        "model": "GLB201ALLB.APZQ",
        "mrp": "37,190.00"
    },
    {
        "category": "Refrigerators",
        "dp": "34,490.00",
        "description": "Smart Inverter Compressor, 10 Yrs. Compressor warranty, Transparent Interior, Toughened Glass, Fastest Ice Making, LVS(100v-290v)",
        "brand": "LG",
        "name": "GLB205APGB.APGQ",
        "image": "URL to Image",
        "capacity": "205L",
        "keywords": ["Smart Inverter", "Toughened Glass", "Fast Ice Making", "Energy Efficient"],
        "model": "GLB205APGB.APGQ",
        "mrp": "38,890.00"
    },
    {
        "category": "Refrigerators",
        "dp": "34,990.00",
        "description": "Smart Inverter Compressor, 10 Yrs. Compressor warranty, Transparent Interior, Toughened Glass, Fastest Ice Making, LVS(100v-290v)",
        "brand": "LG",
        "name": "GLB205ASHB.ASHQ",
        "image": "URL to Image",
        "capacity": "205L",
        "keywords": ["Smart Inverter", "Toughened Glass", "Fast Ice Making", "Energy Efficient"],
        "model": "GLB205ASHB.ASHQ",
        "mrp": "38,190.00"
    },
    {
        "category": "Refrigerators",
        "dp": "35,490.00",
        "description": "Smart Inverter Compressor, 10 Yrs. Compressor warranty, Transparent Interior, Toughened Glass, Fastest Ice Making, LVS(100v-290v)",
        "brand": "LG",
        "name": "GLB205ABHB.ABHQ",
        "image": "URL to Image",
        "capacity": "205L",
        "keywords": ["Smart Inverter", "Toughened Glass", "Energy Efficient", "LVS Range"],
        "model": "GLB205ABHB.ABHQ",
        "mrp": "38,190.00"
    },
    {
        "category": "Refrigerators",
        "dp": "35,490.00",
        "description": "Smart Inverter Compressor, 10 Yrs. Compressor warranty, Transparent Interior, Toughened Glass, Fastest Ice Making, LVS(100v-290v)",
        "brand": "LG",
        "name": "GLB205ARGB.ARGQ",
        "image": "URL to Image",
        "capacity": "205L",
        "keywords": ["Smart Inverter", "Toughened Glass", "Fast Ice Making", "Energy Efficient"],
        "model": "GLB205ARGB.ARGQ",
        "mrp": "38,190.00"
    },
    {
        "category": "Refrigerators",
        "dp": "37,490.00",
        "description": "Smart Inverter Compressor, 10 Yrs. Compressor warranty, Transparent Interior, Toughened Glass, Fastest Ice Making, LVS(100v-290v)",
        "brand": "LG",
        "name": "GLB205ABGB.ABGQ",
        "image": "URL to Image",
        "capacity": "205L",
        "keywords": ["Smart Inverter", "Energy Efficient", "LVS Range", "Fast Ice Making"],
        "model": "GLB205ABGB.ABGQ",
        "mrp": "40,290.00"
    },
    {
        "category": "Refrigerators",
        "dp": "32,490.00",
        "description": "All Transparent parts with Aqua Clear Tinge Cap, Drain Tube, Direct Cooling",
        "brand": "LG",
        "name": "GLB204BPZR.APZQ",
        "image": "URL to Image",
        "capacity": "204L",
        "keywords": ["Aqua Clear", "Direct Cooling", "Transparent Parts", "Drain Tube"],
        "model": "GLB204BPZR.APZQ",
        "mrp": "35,490.00"
    },
    {
        "category": "Refrigerators",
        "dp": "32,990.00",
        "description": "All Transparent parts with Aqua Clear Tinge Cap, Drain Tube, Direct Cooling",
        "brand": "LG",
        "name": "GLB204RDGR.ADGQ",
        "image": "URL to Image",
        "capacity": "204L",
        "keywords": ["Aqua Clear", "Direct Cooling", "Drain Tube", "Transparent Parts"],
        "model": "GLB204RDGR.ADGQ",
        "mrp": "35,090.00"
    },
    {
        "category": "Refrigerators",
        "dp": "31,490.00",
        "description": "All Transparent parts with Aqua Clear Tinge Cap, Drain Tube, Direct Cooling",
        "brand": "LG",
        "name": "GLB204GSJR.ASJQ",
        "image": "URL to Image",
        "capacity": "204L",
        "keywords": ["Aqua Clear", "Direct Cooling", "Drain Tube", "Energy Efficient"],
        "model": "GLB204GSJR.ASJQ",
        "mrp": "32,990.00"
    },
    {
        "category": "Refrigerators",
        "dp": "34,490.00",
        "description": "All Transparent parts with Aqua Clear Tinge Cap, Drain Tube, Direct Cooling",
        "brand": "LG",
        "name": "GLB205ASLB.ASLQ",
        "image": "URL to Image",
        "capacity": "205L",
        "keywords": ["Aqua Clear", "Direct Cooling", "Drain Tube", "Energy Efficient"],
        "model": "GLB205ASLB.ASLQ",
        "mrp": "38,190.00"
    },
    {
        "category": "Refrigerators",
        "dp": "34,990.00",
        "description": "All Transparent parts with Aqua Clear Tinge Cap, Drain Tube, Direct Cooling",
        "brand": "LG",
        "name": "GLB205AELB.AELQ",
        "image": "URL to Image",
        "capacity": "205L",
        "keywords": ["Aqua Clear", "Direct Cooling", "Drain Tube", "Transparent Parts"],
        "model": "GLB205AELB.AELQ",
        "mrp": "38,190.00"
    },
    {
        "category": "Refrigerators",
        "dp": "35,490.00",
        "description": "Smart Inverter Compressor, 10 Yrs. Compressor warranty, Transparent Interior, Toughened Glass, Fastest Ice Making, LVS(100v-290v)",
        "brand": "LG",
        "name": "GLB231ALLB",
        "image": "URL to Image",
        "capacity": "215L",
        "keywords": ["Smart Inverter", "Toughened Glass", "Fast Ice Making", "Energy Efficient"],
        "model": "GLB231ALLB",
        "mrp": "45,290.00"
    },
    {
        "category": "Refrigerators",
        "price": "44,635.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Transparent Interior, Glass Shelves, LVS (100-290)v",
        "brand": "LG",
        "name": "GL-K292SLTL",
        "image": "URL to Image",
        "capacity": "258L",
        "keywords": ["Smart Inverter", "Glass Shelves", "LVS Range", "Transparent Interior"],
        "model": "GL-K292SLTL",
        "mrp": "57,290.00"
    },
    {
        "category": "Refrigerators",
        "price": "48,703.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Transparent Interior, Glass Shelves, LVS (100-290)v",
        "brand": "LG",
        "name": "GL-K272SPTL.ASDQ",
        "image": "URL to Image",
        "capacity": "258L",
        "keywords": ["Smart Inverter", "Glass Shelves", "LVS Range", "Transparent Interior"],
        "model": "GL-K272SPTL.ASDQ",
        "mrp": "62,490.00"
    },
    {
        "category": "Refrigerators",
        "price": "48,703.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Transparent Interior, Glass Shelves, LVS (100-290)v",
        "brand": "LG",
        "name": "GL-K272SPTL.ARGQ",
        "image": "URL to Image",
        "capacity": "258L",
        "keywords": ["Smart Inverter", "Glass Shelves", "LVS Range", "Transparent Interior"],
        "model": "GL-K272SPTL.ARGQ",
        "mrp": "62,490.00"
    },
    {
        "category": "Refrigerators",
        "price": "48,703.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Transparent Interior, Glass Shelves, LVS (100-290)v",
        "brand": "LG",
        "name": "GLK272SPTL.ASQQ",
        "image": "URL to Image",
        "capacity": "258L",
        "keywords": ["Smart Inverter", "Glass Shelves", "LVS Range", "Transparent Interior"],
        "model": "GLK272SPTL.ASQQ",
        "mrp": "62,490.00"
    },
    {
        "category": "Refrigerators",
        "price": "57,404.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Linear Cooling, Door Cooling, Transparent Interior, Glass Shelves, LVS (100-290)v",
        "brand": "LG",
        "name": "GLB292RVBN.APZQ",
        "image": "URL to Image",
        "capacity": "292L",
        "keywords": ["Smart Inverter", "Linear Cooling", "Door Cooling", "Glass Shelves"],
        "model": "GLB292RVBN.APZQ",
        "mrp": "73,590.00"
    },
    {
        "category": "Refrigerators",
        "price": "59,890.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Linear Cooling, Door Cooling, Transparent Interior, Glass Shelves, LVS (100-290)v",
        "brand": "LG",
        "name": "GLB292RVBN.ASCQ",
        "image": "URL to Image",
        "capacity": "292L",
        "keywords": ["Smart Inverter", "Linear Cooling", "Door Cooling", "Glass Shelves"],
        "model": "GLB292RVBN.ASCQ",
        "mrp": "76,790.00"
    },
    {
        "category": "Refrigerators",
        "price": "59,890.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Linear Cooling, Door Cooling, Transparent Interior, Glass Shelves, LVS (100-290)v",
        "brand": "LG",
        "name": "GLB292RVBN.ABCQ",
        "image": "URL to Image",
        "capacity": "292L",
        "keywords": ["Smart Inverter", "Linear Cooling", "Door Cooling", "Glass Shelves"],
        "model": "GLB292RVBN.ABCQ",
        "mrp": "76,790.00"
    },
    {
        "category": "Refrigerators",
        "price": "61,020.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Door Cooling, Transparent Interior, Glass Shelves, LVS (100-290)v",
        "brand": "LG",
        "name": "GLM312RLML.APZQ",
        "image": "URL to Image",
        "capacity": "285L",
        "keywords": ["Smart Inverter", "Door Cooling", "Glass Shelves", "Transparent Interior"],
        "model": "GLM312RLML.APZQ",
        "mrp": "78,290.00"
    },
    {
        "category": "Refrigerators",
        "price": "65,031.50",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Door Cooling, Transparent Interior, Glass Shelves, LVS (100-290)v",
        "brand": "LG",
        "name": "GLM320BPZI.APZQ",
        "image": "URL to Image",
        "capacity": "289L",
        "keywords": ["Smart Inverter", "Door Cooling", "Glass Shelves", "Transparent Interior"],
        "model": "GLM320BPZI.APZQ",
        "mrp": "83,390.00"
    },
    {
        "category": "Refrigerators",
        "price": "63,335.50",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Door Cooling, Transparent Interior, Glass Shelves, LVS (100-290)v",
        "brand": "LG",
        "name": "GLB322RVBN",
        "image": "URL to Image",
        "capacity": "310L",
        "keywords": ["Smart Inverter", "Door Cooling", "Glass Shelves", "Transparent Interior"],
        "model": "GLB322RVBN",
        "mrp": "81,290.00"
    },
    {
        "category": "Refrigerators",
        "price": "63,958.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Door Cooling, Transparent Interior, Glass Shelves, LVS (100-290)v",
        "brand": "LG",
        "name": "GLM332RPZI",
        "image": "URL to Image",
        "capacity": "310L",
        "keywords": ["Smart Inverter", "Door Cooling", "Glass Shelves", "Transparent Interior"],
        "model": "GLM332RPZI",
        "mrp": "81,990.00"
    },
    {
        "category": "Refrigerators",
        "price": "70,003.50",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Transparent Interior, Glass Shelves, 2 times Twist Ice Tray",
        "brand": "LG",
        "name": "GLM380BPZI.APZQ",
        "image": "URL to Image",
        "capacity": "340L",
        "keywords": ["Smart Inverter", "Twist Ice Tray", "Glass Shelves", "Transparent Interior"],
        "model": "GLM380BPZI.APZQ",
        "mrp": "89,790.00"
    },
    {
        "category": "Refrigerators",
        "price": "78,987.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Transparent Interior, Glass Shelves, 2 times Twist Ice Tray",
        "brand": "LG",
        "name": "GLT400CESI.AESQ",
        "image": "URL to Image",
        "capacity": "360L",
        "keywords": ["Smart Inverter", "Twist Ice Tray", "Glass Shelves", "Transparent Interior"],
        "model": "GLT400CESI.AESQ",
        "mrp": "1,01,290.00"
    },
    {
        "category": "Refrigerators",
        "price": "84,072.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Transparent Interior, Glass Shelves, 2 times Twist Ice Tray",
        "brand": "LG",
        "name": "GLM413RLCI",
        "image": "URL to Image",
        "capacity": "360L",
        "keywords": ["Smart Inverter", "Twist Ice Tray", "Glass Shelves", "Transparent Interior"],
        "model": "GLM413RLCI",
        "mrp": "1,07,790.00"
    },
    {
        "category": "Refrigerators",
        "price": "89,157.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Door Cooling, Transparent Interior, Glass Shelves, 2 times Twist Ice Tray",
        "brand": "LG",
        "name": "GLM433PZI",
        "image": "URL to Image",
        "capacity": "422L",
        "keywords": ["Smart Inverter", "Door Cooling", "Glass Shelves", "Twist Ice Tray"],
        "model": "GLM433PZI",
        "mrp": "1,14,390.00"
    },
    {
        "category": "Refrigerators",
        "price": "91,360.50",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Water Dispenser, Door Cooling, Transparent Interior, Glass Shelves, 2 times Twist Ice Tray",
        "brand": "LG",
        "name": "GLB433PZI",
        "image": "URL to Image",
        "capacity": "422L",
        "keywords": ["Smart Inverter", "Water Dispenser", "Door Cooling", "Glass Shelves"],
        "model": "GLB433PZI",
        "mrp": "1,17,190.00"
    },
    {
        "category": "Refrigerators",
        "price": "92,660.00",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, NDC, Toughened Glass, Vitamin Kit, Digital LED Micom, Pull Out Tray, Clean Back",
        "brand": "LG",
        "name": "GLM503PZI",
        "image": "URL to Image",
        "capacity": "471L",
        "keywords": ["Smart Inverter", "NDC", "Vitamin Kit", "Digital LED Micom", "Pull Out Tray"],
        "model": "GLM503PZI",
        "mrp": "1,18,790.00"
    },
    {
        "category": "Refrigerators",
        "price": "98,818.50",
        "description": "Smart Inverter Compressor, 10 Year Compressor Warranty, Water Dispenser, NDC, Toughened Glass, Vitamin Kit, Digital LED Micom, Pull Out Tray, Clean Back",
        "brand": "LG",
        "name": "GLB503PZI",
        "image": "URL to Image",
        "capacity": "471L",
        "keywords": ["Smart Inverter", "Water Dispenser", "NDC", "Vitamin Kit", "Digital LED Micom"],
        "model": "GLB503PZI",
        "mrp": "1,26,690.00"
    },
    {
        "category": "Refrigerators",
        "price": "1,47,860.50",
        "description": "Inverter Linear Compressor, 10 Years Compressor Warranty, Door Cooling, Multi Air Flow, Moist Balance Crisper",
        "brand": "LG",
        "name": "GTM5097PZ",
        "image": "URL to Image",
        "capacity": "547L",
        "keywords": ["Inverter Linear Compressor", "Door Cooling", "Multi Air Flow", "Moist Balance Crisper"],
        "model": "GTM5097PZ",
        "mrp": "1,89,590.00"
    },
    {
        "category": "Refrigerators",
        "price": "2,60,126.00",
        "description": "InstaView Door-in-Door™, Inverter Linear Compressor, Linear Cooling™, Door Cooling+, Hygiene FRESH+™, LG ThinQ (Wi-Fi)",
        "brand": "LG",
        "name": "GFB4539PZ",
        "image": "URL to Image",
        "capacity": "594L",
        "keywords": ["InstaView", "Inverter Linear Compressor", "Linear Cooling", "Door Cooling+"],
        "model": "GFB4539PZ",
        "mrp": "3,33,490.00"
    },
    {
        "category": "Refrigerators",
        "price": "2,44,249.50",
        "description": "Smart Inverter Linear Compressor, Matt Black, Linear Cooling™, Multi Air Flow, Smart Diagnosis, NatureFRESH™",
        "brand": "LG",
        "name": "GFB4532MC",
        "image": "URL to Image",
        "capacity": "594L",
        "keywords": ["Smart Inverter", "Matt Black", "Linear Cooling", "NatureFRESH"],
        "model": "GFB4532MC",
        "mrp": "3,13,190.00"
    },
    {
        "category": "Refrigerators",
        "price": "2,86,398.50",
        "description": "InstaView Door-in-Door™, Inverter Linear Compressor, Linear Cooling™, Door Cooling+, Hygiene FRESH+™, LG ThinQ (Wi-Fi)",
        "brand": "LG",
        "name": "GFQ4919MT",
        "image": "URL to Image",
        "capacity": "594L",
        "keywords": ["InstaView", "Inverter Linear Compressor", "Linear Cooling", "Door Cooling+"],
        "model": "GFQ4919MT",
        "mrp": "3,67,190.00"
    },
    {
        "category": "Refrigerators",
        "price": "1,95,829.00",
        "description": "Inverter Linear Compressor, 10 Year Compressor Warranty, Moist Balance Crisper, LED Lighting, Multi Air Flow, Smart Diagnosis",
        "brand": "LG",
        "name": "GSB6181DS",
        "image": "URL to Image",
        "capacity": "660L",
        "keywords": ["Inverter Linear Compressor", "Moist Balance Crisper", "LED Lighting", "Smart Diagnosis"],
        "model": "GSB6181DS",
        "mrp": "2,51,090.00"
    },
    {
        "category": "Refrigerators",
        "price": "2,20,011.00",
        "description": "Inverter Smart Compressor, 10 Year Compressor Warranty, LINEAR Cooling™, Multi-Air-Flow, Tempered Glass Shelf, Large Capacity",
        "brand": "LG",
        "name": "GSB6432WB",
        "image": "URL to Image",
        "capacity": "659L",
        "keywords": ["Inverter Smart Compressor", "LINEAR Cooling", "Large Capacity", "Tempered Glass Shelf"],
        "model": "GSB6432WB",
        "mrp": "2,82,090.00"
    },
    {
        "category": "Refrigerators",
        "price": "2,20,011.00",
        "description": "Inverter Smart Compressor, 10 Year Compressor Warranty, LINEAR Cooling™, DoorCooling+™, Fresh Zone, Large Capacity",
        "brand": "LG",
        "name": "GSB6472PZ",
        "image": "URL to Image",
        "capacity": "694L",
        "keywords": ["Inverter Smart Compressor", "LINEAR Cooling", "DoorCooling+", "Fresh Zone"],
        "model": "GSB6472PZ",
        "mrp": "2,82,090.00"
    },
    {
        "category": "Refrigerators",
        "price": "2,35,040.00",
        "description": "Inverter Smart Compressor, 10 Year Compressor Warranty, LINEAR Cooling™, DoorCooling+™, Water and Ice Dispenser, UV Nano Technology, LG ThinQ™, Smart Diagnosis",
        "brand": "LG",
        "name": "GSL6172PZ",
        "image": "URL to Image",
        "capacity": "674L",
        "keywords": ["Inverter Smart Compressor", "Water and Ice Dispenser", "UV Nano Technology", "LG ThinQ"],
        "model": "GSL6172PZ",
        "mrp": "3,01,390.00"
    },
    {
        "category": "Refrigerators",
        "price": "3,26,005.00",
        "description": "Inverter Linear Compressor, 10 Year Compressor Warranty, LINEAR Cooling™, Door Cooling+™, Hygiene Fresh, Water and Ice Dispenser, UV Nano Technology, LG ThinQ™, Smart Diagnosis",
        "brand": "LG",
        "name": "GSX6172NS",
        "image": "URL to Image",
        "capacity": "674L",
        "keywords": ["Inverter Linear Compressor", "Hygiene Fresh", "Door Cooling+", "Water and Ice Dispenser"],
        "model": "GSX6172NS",
        "mrp": "4,17,990.00"
    },
    {
        "category": "Refrigerators",
        "price": "3,44,254.50",
        "description": "Smart Inverter Compressor, Linear Cooling+, Door Cooling+, UltraSleek Door, Multi Air Flow, Smart Diagnosis, Matt Black",
        "brand": "LG",
        "name": "GSX6172MC",
        "image": "URL to Image",
        "capacity": "671L",
        "keywords": ["Smart Inverter", "UltraSleek Door", "Linear Cooling", "Multi Air Flow"],
        "model": "GSX6172MC",
        "mrp": "4,41,390.00"
    },
    {
        "category": "Refrigerators",
        "price": "2,30,915.50",
        "description": "Inverter Linear Compressor, 10 Year Compressor Warranty, Water & Dispenser, Door-In-Door, Hygiene Fresh+, Bio Shield, Tempered Glass Shelf",
        "brand": "LG",
        "name": "GSL6012PZ",
        "image": "URL to Image",
        "capacity": "668L",
        "keywords": ["Inverter Linear Compressor", "Water Dispenser", "Hygiene Fresh+", "Tempered Glass Shelf"],
        "model": "GSL6012PZ",
        "mrp": "2,96,090.00"
    },
    {
        "category": "Refrigerators",
        "price": "1,95,659.50",
        "description": "Inverter Linear Compressor, 10 Year Compressor Warranty, Water & Dispenser, Door-In-Door, Hygiene Fresh+, Bio Shield, Tempered Glass Shelf",
        "brand": "LG",
        "name": "GSB6554DS",
        "image": "URL to Image",
        "capacity": "694L",
        "keywords": ["Inverter Linear Compressor", "Water Dispenser", "Door-In-Door", "Bio Shield"],
        "model": "GSB6554DS",
        "mrp": "2,50,890.00"
    },
    {
        "category": "Refrigerators",
        "price": "2,33,853.50",
        "description": "Inverter Linear Compressor, 10 Year Compressor Warranty, Water & Dispenser, Door-In-Door, Hygiene Fresh+, Bio Shield, Tempered Glass Shelf",
        "brand": "LG",
        "name": "GSB6554BM",
        "image": "URL to Image",
        "capacity": "694L",
        "keywords": ["Inverter Linear Compressor", "Water Dispenser", "Hygiene Fresh+", "Bio Shield"],
        "model": "GSB6554BM",
        "mrp": "2,99,890.00"
    },
    {
        "category": "Refrigerators",
        "price": "2,37,000.55",
        "description": "Inverter Linear Compressor, 10 Year Compressor Warranty, Water & Dispenser, Door-In-Door, Hygiene Fresh+, Bio Shield, Tempered Glass Shelf",
        "brand": "LG",
        "name": "GSL6354MC",
        "image": "URL to Image",
        "capacity": "694L",
        "keywords": ["Inverter Linear Compressor", "Water Dispenser", "Hygiene Fresh+", "Bio Shield"],
        "model": "GSL6354MC",
        "mrp": "3,03,890.00"
    },
    {
        "category": "Refrigerators",
        "price": "3,44,254.50",
        "description": "Inverter Linear Compressor, 10 Year Compressor Warranty, Water & Dispenser, Door-In-Door, Hygiene Fresh+, Bio Shield, Tempered Glass Shelf",
        "brand": "LG",
        "name": "GSX6354MC",
        "image": "URL to Image",
        "capacity": "694L",
        "keywords": ["Inverter Linear Compressor", "Water Dispenser", "Hygiene Fresh+", "Bio Shield"],
        "model": "GSX6354MC",
        "mrp": "4,41,390.00"
    },
    {
        "category": "Refrigerators",
        "price": "2,11,423.00",
        "description": "Smart Inverter Compressor, Linear Cooling+, Door Cooling+, UltraSleek Door, Multi Air Flow, Smart Diagnosis, Matt Black",
        "brand": "LG",
        "name": "GSB6473MC",
        "image": "URL to Image",
        "capacity": "694L",
        "keywords": ["Smart Inverter", "Linear Cooling", "UltraSleek Door", "Multi Air Flow"],
        "model": "GSB6473MC",
        "mrp": "2,71,090.00"
    },
    {
        "category": "AirConditioners",
        "price": "83,620.00",
        "description": "Digital display, Heat & Cool, Dual Inverter compressor, 10 years warranty, Anti-virus filter, 70% Energy Saving, 40% Faster Cooling/Heating, 4 in 1 convertible cooling, Ocean Black fin",
        "brand": "LG",
        "name": "S3-W12JA3VA.APWBEXP/ AP6GEXP",
        "image": "URL to Image",
        "capacity": "1 Ton",
        "keywords": ["Digital display", "Dual Inverter", "Anti-virus filter", "Convertible cooling", "Faster Cooling/Heating"],
        "model": "S3-W12JA3VA.APWBEXP",
        "mrp": "1,07,290.00"
    },
    {
        "category": "AirConditioners",
        "price": "1,50,911.50",
        "description": "Digital display, Heat & Cool, Smart Inverter, Dual Inverter compressor 10 years warranty, Anti-bacterial filter, Auto clean, Allergy Care Filter, 70% Energy Saving, 40% Faster Cooling, Low decibel sound, Easy Installation",
        "brand": "LG",
        "name": "S3W24K23VB",
        "image": "URL to Image",
        "capacity": "2 Ton",
        "keywords": ["Smart Inverter", "Anti-bacterial filter", "Auto clean", "Low decibel sound", "Easy Installation"],
        "model": "S3W24K23VB",
        "mrp": "1,93,490.00"
    },
    {
        "category": "AirConditioners",
        "price": "92,773.00",
        "description": "LG ThinQ, Dual Inverter Compressor, 10 Yrs Compressor Warranty, Dual Cool, Faster Cooling, Less Noise, Anti Virus Filter, Monsoon Comfort, Convertible 4 in 1, 4 way swing, + Smart Diagnosis + Jet Mode, +Filter Management, +Advance Schedule",
        "brand": "LG",
        "name": "S3-W12JA3DA",
        "image": "URL to Image",
        "capacity": "1 Ton",
        "keywords": ["LG ThinQ", "Dual Inverter", "Anti Virus Filter", "Convertible 4 in 1", "Smart Diagnosis"],
        "model": "S3-W12JA3DA",
        "mrp": "1,18,990.00"
    },
    {
        "category": "AirConditioners",
        "price": "1,26,729.50",
        "description": "LG ThinQ, Dual Inverter Compressor, 10 Yrs Compressor Warranty, Dual Cool, Faster Cooling, Less Noise, Anti Virus Filter, Monsoon Comfort, Convertible 4 in 1, 4 way swing, + Smart Diagnosis + Jet Mode, +Filter Management, +Advance Schedule",
        "brand": "LG",
        "name": "S3-W18KL3DA",
        "image": "URL to Image",
        "capacity": "1.5 Ton",
        "keywords": ["LG ThinQ", "Dual Inverter", "Faster Cooling", "Monsoon Comfort", "Jet Mode"],
        "model": "S3-W18KL3DA",
        "mrp": "1,59,990.00"
    },
    {
        "category": "AirConditioners",
        "price": "1,18,537.00",
        "description": "LG ThinQ, Dual Inverter Compressor, 10 Yrs Compressor Warranty, Dual Cool, Faster Cooling, Less Noise, Anti Virus Filter, Monsoon Comfort, Convertible 4 in 1, 4 way swing, + Smart Diagnosis + Jet Mode, +Filter Management, +Advance Schedule",
        "brand": "LG",
        "name": "S3-W18KL3VD.AL6G",
        "image": "URL to Image",
        "capacity": "1.5 Ton",
        "keywords": ["LG ThinQ", "Dual Inverter", "Anti Virus Filter", "Monsoon Comfort", "Faster Cooling"],
        "model": "S3-W18KL3VD.AL6G",
        "mrp": "1,51,990.00"
    }
];

module.exports = products;
